@echo off

python .\sample_arm.py
echo "=========================="
python .\sample_armeb.py
echo "=========================="
python .\sample_arm64.py
echo "=========================="
python .\sample_arm64eb.py
echo "=========================="
python .\sample_m68k.py
echo "=========================="
python .\sample_mips.py
echo "=========================="
python .\sample_ppc.py
echo "=========================="
python .\sample_riscv.py
echo "=========================="
python .\sample_s390x.py
echo "=========================="
python .\sample_sparc.py
echo "=========================="
python .\sample_tricore.py
echo "=========================="
python .\sample_x86.py
echo "=========================="
python .\shellcode.py
echo "=========================="
python .\sample_ctl.py
echo "=========================="
python .\sample_network_auditing.py
